/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32103c6_GPIO_Driver.h"
#include "STM32103c6_USART_Driver.h"

void clock_init(){
	 //enable clock for port A and B
		CLK_EN_GPIOA();
		CLK_EN_GPIOB();
		CLK_EN_AFIO();
}

//configuration
USART_Config_t *UsartCfg;
uint16_t ch;
int main(void)
{
	clock_init();
UsartCfg->BaudRate=USART_BaudRate_115200;
UsartCfg->PayloadLen=USART_Payload_len_8;
UsartCfg->Parity=USART_NONE_Parity;
UsartCfg->StopBits=USART_1_StopBit;
UsartCfg->IRQ_Enable=USART_IRQ_Enable_NONE;
UsartCfg->USART_Mode=USART_MODE_TX_RX;

MCAL_USART_init(USART1,UsartCfg) ;
MCAL_USART_GPIO_SetPins(USART1);
	while(1){

		MCAL_USART_ReceiveData(USART1, &ch, enable);
		MCAL_USART_SendData(USART1, &ch, disable);
		}
	return 0;

}
