/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include "Platform_Types.h"

#define RCC_Base  0x40021000
#define Port_A  0x40010800
#define RCC_APB2ENR  *(volatile uint32_t *)(RCC_Base+0x18)
#define GPIOA_RCH    *(volatile uint32_t *)(Port_A+0x04)
#define GPIOA_ODR   *(volatile uint32_t *)(Port_A+0x0c)
typedef union{
	vint32_t allfields;
	struct {
		vint32_t reserved:13;
		vint32_t pin13:1;
	}pin;
}ODR_t;
volatile ODR_t* ODR= (volatile ODR_t*)(Port_A+0x0c);
void main(void)
{
	RCC_APB2ENR |=1<<2;
	GPIOA_RCH &=0xff0fffff;
	GPIOA_RCH |=0x00200000;
	while(1){
		//GPIOA_ODR |=1<<13; //set bit 13
		ODR->pin.pin13=1;
		for(int i=0;i<5000;i++);
		ODR->pin.pin13=0;
				for(int i=0;i<5000;i++);
	}
}
