/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include "Platform_Types.h"
//clock registers
#define RCC_Base  0x40021000
#define RCC_APB2ENR *(volatile uint32_t *)(RCC_Base+0x18) //enable APB2 peripherals
//portA registers
#define Port_A  0x40010800
#define GPIOA_CRH    *(volatile uint32_t *)(Port_A+0x04)
#define GPIOA_CRL    *(volatile uint32_t *)(Port_A+0x00)
#define GPIOA_ODR   *(volatile uint32_t *)(Port_A+0x0c)
#define GPIOA_IDR   *(volatile uint32_t *)(Port_A+0x08)
  //port B
#define Port_B  0x40010C00
#define GPIOB_CRH    *(volatile uint32_t *)(Port_B+0x04)
#define GPIOB_CRL    *(volatile uint32_t *)(Port_B+0x00)
#define GPIOB_ODR   *(volatile uint32_t *)(Port_B+0x0c)
#define GPIOB_IDR   *(volatile uint32_t *)(Port_B+0x08)
void clock_init(){
	RCC_APB2ENR|=1<<2; //enable clock for gpioA
	RCC_APB2ENR|=1<<3; //enable clock for GPIO_B
}
void GPIO_init(){
	GPIOA_CRL |=0b0100<<4; //set portA.1 as floating input
	GPIOA_CRH &=0xff0fffff;
	GPIOA_CRH |=0x00400000; //set portA.13 as floating input
	//port B
	GPIOB_CRL &=~(0b1111<<4);
	GPIOB_CRL |=0b0001<<4; //set portB.1 as output
	GPIOB_CRH &=0xff0fffff;
	GPIOB_CRH |=0x00100000; //set portB.13 as output
}
void delay(){
	for(int i=0;i<5000;i++);
}
int main(void)
{
	clock_init();
	GPIO_init();

	while(1){
		if((GPIOA_IDR&(1<<1))>>1==0){
				GPIOB_ODR ^=1<<1;
		while((GPIOA_IDR&(1<<1))>>1==0);
		}
		if((GPIOA_IDR&(1<<13))>>13==1){
						GPIOB_ODR ^=1<<13;
				}
		delay();
	}
return 0;
}
