/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include "Platform_Types.h"

#define SYSCTL_RCGC2_Base  0x400FE000
#define Port_F  0x40025000
#define SYSCTL  *((volatile uint32_t *)(SYSCTL_RCGC2_Base+0x108))
#define GPIO_portF_DATA  *((volatile uint32_t *)(Port_F+0x3FC))
#define GPIO_portF_DIR   *((volatile uint32_t *)(Port_F+0x400))
#define GPIO_portF_DEN  *((volatile uint32_t *)(Port_F+0x51C))
void main(void)
{
	SYSCTL|=0x00000020; //enable port F
	volatile uint32_t delay;
	for(delay=0;delay<5000;delay++); //wait for port to be enabled
	GPIO_portF_DEN  |=1<<3;
	GPIO_portF_DIR  |=1<<3;
	while(1){
		GPIO_portF_DATA |=1<<3;
		    for(delay=0;delay<50000;delay++);
		GPIO_portF_DATA &=~(1<<3);
			for(delay=0;delay<50000;delay++);
	}
}
