/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include "Platform_Types.h"
//clock registers
#define RCC_Base  0x40021000
#define RCC_APB2ENR *(volatile uint32_t *)(RCC_Base+0x18) //enable APB2 peripherals
//portA registers
#define Port_A  0x40010800
#define GPIOA_CRH    *(volatile uint32_t *)(Port_A+0x04)
#define GPIOA_CRL    *(volatile uint32_t *)(Port_A+0x00)
#define GPIOA_ODR   *(volatile uint32_t *)(Port_A+0x0c)
//EXTI registers
#define EXTI_base    0x40010400
#define EXTI_RSTR   *(volatile uint32_t *)(EXTI_base+0x08)
#define EXTI_IMR   *(volatile uint32_t *)(EXTI_base+0x00)
#define EXTI_PR   *(volatile uint32_t *)(EXTI_base+0x14)
//NVIC
#define NVIC  *(volatile uint32_t *)(0xE000E100)
void clock_init(){
	RCC_APB2ENR|=1<<2; //enable clock for gpioA
	RCC_APB2ENR|=1<<0; //enable clock for AFIO
}
void GPIO_init(){
	GPIOA_CRL |=1<<2; //set portA as floating input
	GPIOA_CRH &=0xff0fffff;
	GPIOA_CRH |=0x00200000; //set bit 13 as output
}
int main(void)
{
	clock_init();
	GPIO_init();
	EXTI_IMR |=1<<0; //enable interrupt(mask) for exti0
	EXTI_RSTR |=1<<0; //rising edge
    NVIC|=1<<6; //irq6 for EXTiI0
	while(1);

	return 0;
}
void EXTI0_IRQHandler  (){
	GPIOA_ODR ^=1<<13; //toggle led on pin13
	EXTI_PR |=1<<0; //clear pending interrupt
}
